### ISSUE TITLE
"target_ns" is not defined, when deleting an openunison

### ISSUE THREAD

**Issue by dkulchinsky** [TremoloSecurity/openunison-k8s-operator#40]
with latest version of the operator, and latest chart.

The operator throws the following exception when deleting an openunison:
```
javax.script.ScriptException: ReferenceError: "target_ns" is not defined in <eval> at line number 919
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at com.tremolosecurity.kubernetes.artifacts.util.K8sWatcher.processEvent(K8sWatcher.java:331)
	at com.tremolosecurity.kubernetes.artifacts.util.K8sWatcher.watchUri(K8sWatcher.java:153)
	at com.tremolosecurity.kubernetes.artifacts.run.RunWatch.run(RunWatch.java:38)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:919 ReferenceError: "target_ns" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1442)
	at jdk.nashorn.internal.scripts.Script$Recompilation$123$33423$\^eval\_.delete_k8s_deployment(<eval>:919)
	at jdk.nashorn.internal.scripts.Script$Recompilation$122$52A$\^eval\_.on_watch(<eval>:79)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 5 more
```

should this:
https://github.com/TremoloSecurity/openunison-k8s-operator/blob/574b7d24cbf0d38aba79769ed4e4b93c0d4c7f42/src/main/js/deploy-upstream-k8s.js#L919
use `k8s_namespace` instead of `target_ns`?

**Comment by mlbiam** [comment]
verified fix.  kill your container to get the latest
